### PR TITLE
Vue Component: Tables

### PR DESCRIPTION
**Pull request by Azbury**
# Tables

## Table Component

Props:
- unresponsive: Boolean prop where if defined the table will have the class `unresponsive` added
- hoverOff: Boolean prop where if defined the table will have the class `table--no-hover` added
- headers: Array prop used to populate the headers of the table

## Table Row Component

Used to separate rows in the markup

## Table Cell Component

Props:
- label: String prop used to set the `data-label` attribute

#### Code

``` html
<pui-table :headers="['Dog', 'Cat', 'Human']">
      <pui-table-row>
        <pui-table-cell label="Dog">Pit Bull</pui-table-cell>
        <pui-table-cell label="Cat">Short Hair</pui-table-cell>
        <pui-table-cell label="Human">Austin</pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell label="Dog">German Shepherd</pui-table-cell>
        <pui-table-cell label="Cat">Long Hair</pui-table-cell>
        <pui-table-cell label="Human">Kevin</pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell label="Dog">Poodle</pui-table-cell>
        <pui-table-cell label="Cat">Maine Coon</pui-table-cell>
        <pui-table-cell label="Human">Beth</pui-table-cell>
      </pui-table-row>
</pui-table>
```

#### Screenshot

image

image

#### Code

``` html
<pui-table :headers="['Dog', 'Cat', 'Human']" unresponsive>
      <pui-table-row>
        <pui-table-cell label="Dog">Pit Bull</pui-table-cell>
        <pui-table-cell label="Cat">Short Hair</pui-table-cell>
        <pui-table-cell label="Human">Austin</pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell label="Dog">German Shepherd</pui-table-cell>
        <pui-table-cell label="Cat">Long Hair</pui-table-cell>
        <pui-table-cell label="Human">Kevin</pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell label="Dog">Poodle</pui-table-cell>
        <pui-table-cell label="Cat">Maine Coon</pui-table-cell>
        <pui-table-cell label="Human">Beth</pui-table-cell>
      </pui-table-row>
</pui-table>
```

#### Screenshot

image

#### Code

``` html
<pui-table :headers="['Dog', 'Cat', 'Human']" hoverOff>
      <pui-table-row>
        <pui-table-cell label="Dog">Pit Bull</pui-table-cell>
        <pui-table-cell label="Cat">Short Hair</pui-table-cell>
        <pui-table-cell label="Human">Austin</pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell label="Dog">German Shepherd</pui-table-cell>
        <pui-table-cell label="Cat">Long Hair</pui-table-cell>
        <pui-table-cell label="Human">Kevin</pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell label="Dog">Poodle</pui-table-cell>
        <pui-table-cell label="Cat">Maine Coon</pui-table-cell>
        <pui-table-cell label="Human">Beth</pui-table-cell>
      </pui-table-row>
</pui-table>
```

#### Screenshot

image

### Unresponsive Table without Data Labels

If a table has the unresponsive tag on it, you do not have to define `label` props for the `pui-table-cell` components.

#### Code

``` html
<pui-table :headers="['Dog', 'Cat', 'Human']" unresponsive>
      <pui-table-row>
        <pui-table-cell>Pit Bull</pui-table-cell>
        <pui-table-cell>Short Hair</pui-table-cell>
        <pui-table-cell>Austin</pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell>German Shepherd</pui-table-cell>
        <pui-table-cell>Long Hair</pui-table-cell>
        <pui-table-cell>Kevin</pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell>Poodle</pui-table-cell>
        <pui-table-cell>Maine Coon</pui-table-cell>
        <pui-table-cell>Beth</pui-table-cell>
      </pui-table-row>
</pui-table>
```

#### Screenshot

image

### Table with Missing Header Slots

If you want a table where a particular header slot is missing, you can use a blank string for that index in the array.

#### Code

``` html
<pui-table :headers="['', 'Option One', 'Option Two']" unresponsive>
      <pui-table-row>
        <pui-table-cell>Desc</pui-table-cell>
        <pui-table-cell>Pork Buns</pui-table-cell>
        <pui-table-cell>Pork Buns</pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell>Price</pui-table-cell>
        <pui-table-cell>$5.00</pui-table-cell>
        <pui-table-cell>$9.00</pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell>Quanity</pui-table-cell>
        <pui-table-cell>5</pui-table-cell>
        <pui-table-cell>2</pui-table-cell>
      </pui-table-row>
</pui-table>
```

#### Screenshot

image

#### Code

``` html
<pui-table :headers="['Dog', 'Cat', 'Human']">
      <pui-table-row>
        <pui-table-cell label="Dog"><img src="./assets/dog1.jpg" alt="dog" style="height: 200px"></pui-table-cell>
        <pui-table-cell label="Cat"><img src="./assets/yuumi.jpg" alt="cat" style="height: 200px"></pui-table-cell>
        <pui-table-cell label="Human"><i class='pi-user-solid pi-xxl'></i></pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell label="Dog"><img src="./assets/dog2.jpg" alt="dog" style="height: 200px"></pui-table-cell>
        <pui-table-cell label="Cat"><i class='pi-twitter pi-xxl'></i></pui-table-cell>
        <pui-table-cell label="Human"><i class='pi-ritter pi-xxl'></i></pui-table-cell>
      </pui-table-row>
      <pui-table-row>
        <pui-table-cell label="Dog"><i class='pi-dollar pi-xxl'></i></pui-table-cell>
        <pui-table-cell label="Cat"><img src="./assets/momo.jpg" alt="cat" style="height: 200px"></pui-table-cell>
        <pui-table-cell label="Human"><i class='pi-bank pi-xxl'></i></pui-table-cell>
      </pui-table-row>
</pui-table>
```

#### Screenshot

image

### CODE REVIEW

**Comment by mrtrimble** [comment]
Only question I have is what if someone wanted to include something other than text in a table cell, like an image or icon?

**Comment by Azbury** [comment]
That is a good point, for the most part I have only seen text included in table examples but it should definitely be flexible. I'm going to work on creating a `<pui-table-cell>` component so you can add whatever you want to the cell.

**Comment by Azbury** [comment]
I refactored to create a `<pui-table-cell>` component. Helps clean up the markup as well as giving flexibility to developers to use images or icons in table cells.

**Review by mrtrimble — APPROVED** [review]

**Comment by jpvicari** [comment]
Is the `<pui-table-row>` component necessary at this point? Is there a future proof advantage here?

**Comment by mrtrimble** [comment]
I could see it being used to generate rows dynamically like:

```html
<pui-table-row v-for="item in items">
  <pui-table-cell>{{item.name}}</pui-table-cell>
  <pui-table-cell>{{item.address}}</pui-table-cell>
</pui-table-row>
```

Also if you wanted to apply specific stylings to a row you can add a class attribute directly to the row.

It is a little like reinventing the wheel, but it keeps consistent with other components.

**Comment by jpvicari** [comment]
Yeah, I don't necessarily think there is a right or wrong way, consistency is probably the best argument here, and possibly for future enhancements. If there is no `<pui-table-row>` component, you can always apply the loops and classes directly on the `<tr>`...

**Comment by mrtrimble** [comment]
Very true! 

I just checked out how bootstrap handles tables and... actually they do a lot, wow:
[https://bootstrap-vue.org/docs/components/table](https://bootstrap-vue.org/docs/components/table)

Though for a [simple table](https://bootstrap-vue.org/docs/components/table#simple-tables) they are doing something similar to what @Azbury has built here.

**Review by jpvicari — APPROVED** [review]

**Pull request merged**
